const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.solid,
		C3.Behaviors.Timer,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Browser,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Behaviors.Physics,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Text.Acts.Destroy,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Text.Cnds.OnCreated,
		C3.Plugins.Text.Exps.X,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.System.Cnds.IsBetweenAngles,
		C3.Plugins.Touch.Exps.AngleAt,
		C3.Behaviors.Platform.Acts.FallThrough,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Browser.Acts.Reload,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Acts.SetBoolVar
	];
};
self.C3_JsPropNameTable = [
	{Firstlevelbg: 0},
	{left: 0},
	{right: 0},
	{MoveTo: 0},
	{Platform: 0},
	{BoundToLayout: 0},
	{Solid: 0},
	{rolling_barrel: 0},
	{platform: 0},
	{id: 0},
	{left_right: 0},
	{change_anim: 0},
	{barrel_delete: 0},
	{stair: 0},
	{Marleft: 0},
	{Marright: 0},
	{dead: 0},
	{hammer: 0},
	{canmove: 0},
	{Timer: 0},
	{Mario_player: 0},
	{Touch: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{AJAX: 0},
	{JSON: 0},
	{Browser: 0},
	{moveX: 0},
	{oilbarrel: 0},
	{Barrel_fire: 0},
	{princess: 0},
	{helpTxt: 0},
	{StandBarrel: 0},
	{BarrelSpawner: 0},
	{DKong: 0},
	{Pin: 0},
	{AddScoreBarrel: 0},
	{HightScores: 0},
	{Fade: 0},
	{addScoresAnim: 0},
	{HammerBonus: 0},
	{MarioTopGreen: 0},
	{Physics: 0},
	{bluebarrel: 0},
	{MarioHealth: 0},
	{LocalStorage: 0},
	{level: 0},
	{PrincessTrigger: 0},
	{Heart: 0},
	{LoadingText: 0},
	{MarioLoading: 0},
	{loading_barrel: 0},
	{GoLeft: 0},
	{GoRight: 0},
	{FireBoy: 0},
	{fireTriggerRight: 0},
	{fireTriggerLeft: 0},
	{BonusTxt: 0},
	{PlayerScores: 0},
	{KongAnim: 0},
	{Zaklepka: 0},
	{bonus: 0},
	{AddScoreFire: 0},
	{canup: 0},
	{candown: 0},
	{TX: 0},
	{PScores: 0},
	{PBonus: 0},
	{FireBoySpeed: 0},
	{MHealth: 0},
	{RollingSpawn: 0},
	{NowLevel: 0},
	{GotoGame: 0}
];

self.InstanceType = {
	Firstlevelbg: class extends self.ISpriteInstance {},
	rolling_barrel: class extends self.ISpriteInstance {},
	platform: class extends self.ISpriteInstance {},
	left_right: class extends self.ISpriteInstance {},
	change_anim: class extends self.ISpriteInstance {},
	barrel_delete: class extends self.ISpriteInstance {},
	stair: class extends self.ISpriteInstance {},
	Mario_player: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Browser: class extends self.IInstance {},
	moveX: class extends self.ISpriteInstance {},
	oilbarrel: class extends self.ISpriteInstance {},
	Barrel_fire: class extends self.ISpriteInstance {},
	princess: class extends self.ISpriteInstance {},
	helpTxt: class extends self.ISpriteInstance {},
	StandBarrel: class extends self.ISpriteInstance {},
	BarrelSpawner: class extends self.ISpriteInstance {},
	DKong: class extends self.ISpriteInstance {},
	AddScoreBarrel: class extends self.ISpriteInstance {},
	HightScores: class extends self.ITextInstance {},
	addScoresAnim: class extends self.ITextInstance {},
	HammerBonus: class extends self.ISpriteInstance {},
	MarioTopGreen: class extends self.ISpriteInstance {},
	bluebarrel: class extends self.ISpriteInstance {},
	MarioHealth: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	PrincessTrigger: class extends self.ISpriteInstance {},
	Heart: class extends self.ISpriteInstance {},
	LoadingText: class extends self.ITextInstance {},
	MarioLoading: class extends self.ISpriteInstance {},
	loading_barrel: class extends self.ISpriteInstance {},
	FireBoy: class extends self.ISpriteInstance {},
	fireTriggerRight: class extends self.ISpriteInstance {},
	fireTriggerLeft: class extends self.ISpriteInstance {},
	BonusTxt: class extends self.ITextInstance {},
	PlayerScores: class extends self.ITextInstance {},
	KongAnim: class extends self.ISpriteInstance {},
	Zaklepka: class extends self.ISpriteInstance {},
	bonus: class extends self.ISpriteInstance {},
	AddScoreFire: class extends self.ISpriteInstance {},
	canup: class extends self.ISpriteInstance {},
	candown: class extends self.ISpriteInstance {}
}